### DISCUSSION TITLE
nGrinder

### DISCUSSION THREAD

**Discussion by joonhoekim** [mannazo/mannazo#8] [GroupStudy]
스트레스테스트, 부하테스트를 위한 오픈소스 프로젝트
- 네이버에서 관리함
- 컨트롤러가 다수의 에이전트들에게 요청을 하게 만들고, 요청에 얼마나 정상적인 응답이 왔는지 확인하는 방식
  - 컨트롤러와 에이전트는 동일한 PC여도 됨.
  - 어떤 요청을 하는지(가상의 유저가 어떤 행동을 하는지) 설정 가능 

로컬에서 war 을 jvm에 올려 실행하는 방법도 있으나, 가장 간단한 방법은 docker 이미지를 이용하는 것.

이미지 또한 컨트롤러/에이전트로 나뉘어있음. 따라서 간편하게 docker-compose를 이용할 수 있음.

아래 코드를 `docker-compose.yml` 파일을 만들어서 넣고, 해당 경로에서 `docker-compose up` 명령어를 실행해주면 컨트롤러/에이전트 바로 띄우고 연결 가능함.

`9000:80` 은 컨트롤러 웹UI로 들어가는 포트를 결정하는 부분인데, 9000번 말고 다른 포트를 써도 무방함.
```
version: '3.8'
services:
  controller:
    image: ngrinder/controller:latest
    restart: always
    ports: 
      - "9000:80"
      - "16001:16001"
      - "12000-12009:12000-12009"
    volumes:
      - ./ngrinder-controller:/opt/ngrinder-controller
  agent:
    image: ngrinder/agent:latest
    restart: always
    links:    
      - controller
```

이후에는 script를 작성하고, performance test에서 해당 script 를 선택하여 에이전트 수, 유저 수 등 성능 테스트를 진행할 수 있음.
